env:
  browser: false
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: {
  radix: ["error", "as-needed"],
  no-restricted-syntax: "off",
  import/extensions: "off"
  indent: ["error", 4]
}
